### ISSUE TITLE
rtm_send_message not documented correctly

### ISSUE THREAD

**Issue by ns-phennessy** [slackhq/python-rtmbot#14]
The readme says I should be able to pass a dict to `slackclient.rtm_send_message` but the source has 2 positional arguments.

It also doesnt look like it can recognize anything but the ID of the channel itself

**Comment by oisino** [comment]
I got it to work with sc.rtm_send_message(channel="Channel ID",message="message")

**Comment by kenden** [comment]
This issue is in the wrong repo. It should be here: 
https://github.com/slackhq/python-slackclient

The readme there says:
SlackClient.rtm_send_message([channel, message]) Sends the text in [message] to [channel], which can be a name or identifier i.e. "#general" or "C182391"

It does not say it can take a dict ?

**Comment by dalanmiller** [comment]
At this page under "Sending messages" it shows that one can send JSON/Dict?

https://api.slack.com/rtm

**Comment by jammons** [comment]
Closing this issue as @kenden points out, it belongs in the https://github.com/slackhq/python-slackclient repository.
