### ISSUE TITLE
Having an issue of import by filename not supported

### ISSUE THREAD

**Issue by brizzbane** [slackhq/python-rtmbot#3]
running on windows

**Comment by Vaune** [comment]
Was getting the same error.  I imported the library imp and loaded the plugin files using imp.load_source(plugin_name, full_path_to_plugin_file)

**Comment by afunsten** [comment]
can you give a little more detail about the workaround?

**Comment by TaylorBenner** [comment]
@afunsten Sure.  I'm pretty inexperienced with python but I was able to get this file to work by switching the  Plugin class, init to use the imp library.  Instead of referencing __import__ for the plugin modules, I use imp.load_source and provide the full path and file name as follows:

from imp import load_source
parts = name.split("\\")
self.module  = load_source(parts[1], 'full\path\to\plugin\file\\' + parts[1] + '.py')

Instead of the current code on line 85:
self.module = __import__(name)


This problem exists because of how Windows handles importing files via relative path to my knowledge.
