### ISSUE TITLE
Question on the structure

### ISSUE THREAD

**Issue by zenvisuals** [slackhq/python-rtmbot#30]
Hi,

Thanks for creating this project for us to reference on.

Correct me if I'm wrong, it seems like the bot would have to go through all the plugins, all the outputs, find the output with some values in it and then only the bot will send out the value to the channel.

Just wondering if there is a reason behind this structure, is it possible we only call the plugin when we need it and not go through every single one of them for every message the bot receive?

Thanks!
Zhiquan

**Comment by jcamilli** [comment]
Yeah I think this is the way of Slack. Every message gets sent to every bot.

**Comment by jammons** [comment]
Because this project is structured around plugins, it does what you described above. This is unlikely to be an issue unless you have **a lot** of bots and messages coming through. You could certainly just use the  https://github.com/slackhq/python-slackclient to write your own tool at a lower level if you want to improve the performance of your bot though.
