### ISSUE TITLE
b' in slack channel

### ISSUE THREAD

**Issue by ScubaDrew** [slackhq/python-rtmbot#45]
Hello,

My bot is displaying all messages as follows:

devopsbotBOT [10:33 AM] 
b'drew: Hello.'

How can i remove the b' from this?

Thanks,
Drew

**Comment by jammons** [comment]
Hi Drew,

What code are you using to generate these messages? (What does your plugin code look like?)

-Jeff

**Comment by ScubaDrew** [comment]
Hi @jammons -- 

I just modified the canary sample a bit -- 

`outputs.append([data['channel'], "@" + ud['name'] + ": Hello."])`

This only happens when I am using virtualenv with python 3. I reverted back to Python 2.7.6 and it works fine with no code changes.

Thanks for your time.

Drew

**Comment by jammons** [comment]
Ah, that is odd. Looks like this is likely the reason: https://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal

Python is treating the string as a byte literal instead of a string. I'm not an expert on this, but I would guess that add `str()` around this `[data['channel'], "@" + ud['name'] + ": Hello."]` would fix it. Care to give that a shot and let me know? I'd need to do some digging to figure out why Python 3 is treating that as a byte literal...

**Comment by ScubaDrew** [comment]
Thanks @jammons -- I did find that info as well, and tried str() Did not do the trick unfortunately.

**Comment by cajturner** [comment]
I also encountered this with Python 3. By editing core.py line 104:
``` message = output[1].encode('ascii', 'ignore') ```
to
``` message = output[1] ```
I was able to receive plain text messages. Not sure what this effects but it's a quick work around

**Comment by ScubaDrew** [comment]
Thanks @cajturner -- I'll give that a shot if I get forced back into python3

**Comment by jammons** [comment]
I just merged a fix for this situation into master, so things should work in both py2.7 and py3.x. If anyone runs into issues again, please let us know.
